export type ColorScheme = 'light' | 'dark'

export type Space =
    | '--space-3xs'
    | '--space-2xs'
    | '--space-xs'
    | '--space-s'
    | '--space-m'
    | '--space-l'
    | '--space-xl'
    | '--space-2xl'
    | '--space-3xl'
    | '--space-4xl'
    | '--space-5xl'
    | '--space-6xl'
    | '--space-7xl'
    | '--space-8xl'
    | '--space-3xs-2xs'
    | '--space-2xs-xs'
    | '--space-xs-s'
    | '--space-s-m'
    | '--space-m-l'
    | '--space-l-xl'
    | '--space-xl-2xl'
    | '--space-2xl-3xl'
    | '--space-3xl-4xl'
    | '--space-4xl-5xl'
    | '--space-5xl-6xl'
    | '--space-6xl-7xl'
    | '--space-7xl-8xl'
    | '--space-s-l'
    | '--border-radius-outer'
    | '--border-radius-inner'
    | '--header-height'

export type FontSize = '--fs-0' | '--fs-1' | '--fs-2' | '--fs-3'

export type ThemeColor =
    | '--body-background-color'
    | '--body-text-color'
    | '--body-text-color-variant'
    | '--header-background-color'
    | '--header-text-color'
    | '--header-button-background'
    | '--header-button-outline'
    | '--button-text-color'
    | '--button-text-color-active'
    | '--button-outline-active'
    | '--button-primary-background'
    | '--button-primary-background-hover'
    | '--button-primary-background-active'
    | '--button-primary-outline-hover'
    | '--button-secondary-background'
    | '--button-secondary-background-hover'
    | '--button-secondary-background-active'
    | '--button-secondary-outline-hover'
    | '--button-outlined-background-active'
    | '--button-outlined-outline'
    | '--button-outlined-outline-hover'
    | '--input-placeholder-color'
    | '--input-background-focus'
    | '--input-border-color'
    | '--input-border-color-focus'
    | '--checkbox-stroke'
    | '--checkbox-fill'
    | '--error-color'
